services:
    server:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 9091:80
        environment:
            DOTNET_ENVIRONMENT: "Production"
            DOTNET_ConnectionStrings__SqlDatabase: "Server=db;Database=myDataBase;User ID=sa;Password=example_123;"
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "example_123"
        ports:
            - "1433:1433"
